<h2 style = "color:green"> P1 </h1>
<hr style = 'height: 2px'>


In [3]:
import numpy as np
print()
x = np.diag(np.full(3,9))
print(x)


[[9 0 0]
 [0 9 0]
 [0 0 9]]


<h2 style = "color:green"> P2 </h1>
<hr style = 'height: 2px'>


In [8]:
import numpy as np
print()

x = np.arange(2,33,2).reshape((4,4))
std = x.std()
avg = x.mean()
boolean =(x > (avg - std)) & (x < (avg + std))

print(x)
print(x[boolean])


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[ 8 10 12 14 16 18 20 22 24 26]


<h2 style = "color:green"> P3 </h1>
<hr style = 'height: 2px'>

In [11]:
import numpy as np

x = np.zeros((9,9),dtype = int)

print(x)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


<h2 style = "color:green"> P4 </h1>
<hr style = 'height: 2px'>

In [5]:
import numpy as np

n = int(input("enter a number:\n"))
print()

x = np.zeros((n,n))

#columns
z = np.arange(1,n+1)
print(x+z)

#Rows
z = np.arange(1,n+1).reshape(n,1)
print(x + z)

enter a number:
5

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]
